//Hand-generated for now, but will be auto-generated by main.py script that trains the DT and export to this file.
#include "../include/project_features.h"

//S port, D port, protocol, packet size
#define FEATURES (F_S_PORT | F_D_PORT | F_PROTOCOL | F_PKT_SIZE)
#define FEATURE_NB 4