// Auto-generated by main.py.
// Include this file in dt_xdp.xdp.c to load the feature vector descriptor.

#define DT_NODE_NB 7

#define FEATURE_NB 6
#define FEATURES (F_S_PORT|F_D_PORT|F_PROTOCOL|F_PKT_SIZE|F_IAT_MEAN|F_IAT)
