// Auto-generated by main.py.
// Include this file in dt_xdp.usr.c to load the decision tree.

//#define DT_NODE_NB 63

static struct dt_node trained_dt_nodes[] = {
    { .feature = 0xA3, .threshold = 210 },  // [0] feat_id=3 thresh=210 pass_left=1 pass_right = 1
    { .feature = 0xE0, .threshold = 32621 },  // [1] feat_id=0 thresh=32621 pass_left=0 pass_right = 0
    { .feature = 0xA1, .threshold = 443 },  // [2] feat_id=1 thresh=443 pass_left=1 pass_right = 1
    { .feature = 0xA0, .threshold = 488 },  // [3] feat_id=0 thresh=488 pass_left=0 pass_right = 0
    { .feature = 0xE1, .threshold = 38 },  // [4] feat_id=1 thresh=38 pass_left=1 pass_right = 1
    { .feature = 0x60, .threshold = 32814 },  // [5] feat_id=0 thresh=32814 pass_left=0 pass_right = 0
    { .feature = 0xA0, .threshold = 512 },  // [6] feat_id=0 thresh=512 pass_left=0 pass_right = 0
    { .feature = 0xE0, .threshold = 136 },  // [7] feat_id=0 thresh=136 pass_left=0 pass_right = 0
    { .feature = 0x60, .threshold = 992 },  // [8] feat_id=0 thresh=992 pass_left=0 pass_right = 0
    { .feature = 0x00, .threshold = 0 },  // [9] leaf / undef
    { .feature = 0xE3, .threshold = 0 },  // [10] feat_id=3 thresh=0 pass_left=1 pass_right = 1
    { .feature = 0xA0, .threshold = 520 },  // [11] feat_id=0 thresh=520 pass_left=0 pass_right = 0
    { .feature = 0xE1, .threshold = 438 },  // [12] feat_id=1 thresh=438 pass_left=1 pass_right = 1
    { .feature = 0x00, .threshold = 0 },  // [13] leaf / undef
    { .feature = 0x21, .threshold = 5353 },  // [14] feat_id=1 thresh=5353 pass_left=1 pass_right = 1
    { .feature = 0xE1, .threshold = 2893 },  // [15] feat_id=1 thresh=2893 pass_left=1 pass_right = 1
    { .feature = 0xE1, .threshold = 59469 },  // [16] feat_id=1 thresh=59469 pass_left=1 pass_right = 1
    { .feature = 0x00, .threshold = 0 },  // [17] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [18] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [19] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [20] leaf / undef
    { .feature = 0xE0, .threshold = 50378 },  // [21] feat_id=0 thresh=50378 pass_left=0 pass_right = 0
    { .feature = 0xE3, .threshold = 86 },  // [22] feat_id=3 thresh=86 pass_left=1 pass_right = 1
    { .feature = 0x00, .threshold = 0 },  // [23] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [24] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [25] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [26] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [27] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [28] leaf / undef
    { .feature = 0x61, .threshold = 5336 },  // [29] feat_id=1 thresh=5336 pass_left=1 pass_right = 1
    { .feature = 0x20, .threshold = 47525 },  // [30] feat_id=0 thresh=47525 pass_left=0 pass_right = 0
    { .feature = 0x00, .threshold = 0 },  // [31] leaf / undef
    { .feature = 0xE1, .threshold = 50570 },  // [32] feat_id=1 thresh=50570 pass_left=1 pass_right = 1
    { .feature = 0x00, .threshold = 0 },  // [33] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [34] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [35] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [36] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [37] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [38] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [39] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [40] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [41] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [42] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [43] leaf / undef
    { .feature = 0xE0, .threshold = 59688 },  // [44] feat_id=0 thresh=59688 pass_left=0 pass_right = 0
    { .feature = 0xE0, .threshold = 37438 },  // [45] feat_id=0 thresh=37438 pass_left=0 pass_right = 0
    { .feature = 0xE1, .threshold = 95 },  // [46] feat_id=1 thresh=95 pass_left=1 pass_right = 1
    { .feature = 0x00, .threshold = 0 },  // [47] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [48] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [49] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [50] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [51] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [52] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [53] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [54] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [55] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [56] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [57] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [58] leaf / undef
    { .feature = 0x20, .threshold = 1368 },  // [59] feat_id=0 thresh=1368 pass_left=0 pass_right = 0
    { .feature = 0x00, .threshold = 0 },  // [60] leaf / undef
    { .feature = 0x00, .threshold = 0 },  // [61] leaf / undef
    { .feature = 0x23, .threshold = 288 },  // [62] feat_id=3 thresh=288 pass_left=1 pass_right = 1
};
/*
              precision    recall  f1-score   support

      BENIGN       0.96      1.00      0.98      6036
   MALICIOUS       1.00      0.99      1.00     50498

    accuracy                           1.00     56534
   macro avg       0.98      1.00      0.99     56534
weighted avg       1.00      1.00      1.00     56534
*/