// Auto-generated by main.py.
// Include this file in dt_xdp.usr.c to load the decision tree.

//#define DT_NODE_NB 15

static struct dt_node trained_dt_nodes[] = {
    { .feature = 0b10100010, .threshold = 16 }, //protocol feature : 3rd feature in the vector so index 2
    { .feature = 0x00, .threshold = 0},            //placeholder node.
    { .feature = 0b01100010, .threshold = 17 } 
};
    /*
                root : feature = protocol, thresh = 16.
                /                       \
                <=16                      >16
               /                           \
            PASS              node 2: feature = protocol, thresh = 17
                                    /               \
                               ==17                  > 17
                                /                       \
                            DROP                        PASS

    */