// Auto-generated by main.py.
// Include this file in dt_xdp.usr.c to load the decision tree.

#define DT_NODE_NB 15

static __u32 trained_dt_nodes[] = {
    0x0000D20E,  // [0] feat_id=3 thresh=210 pass_left=1 pass_right=0
    0x00BFDE03,  // [1] feat_id=0 thresh=49118 pass_left=1 pass_right=1
    0x00000B0A,  // [2] feat_id=2 thresh=11 pass_left=1 pass_right=0
    0x00000B0A,  // [3] feat_id=2 thresh=11 pass_left=1 pass_right=0
    0x00002807,  // [4] feat_id=1 thresh=40 pass_left=1 pass_right=1
    0x00010507,  // [5] feat_id=1 thresh=261 pass_left=1 pass_right=1
    0x012E4311,  // [6] feat_id=4 thresh=77379 pass_left=0 pass_right=1
    0x000AE703,  // [7] feat_id=0 thresh=2791 pass_left=1 pass_right=1
    0x00047006,  // [8] feat_id=1 thresh=1136 pass_left=1 pass_right=0
    0x00000000,  // [9] leaf / undef
    0x0000000F,  // [10] feat_id=3 thresh=0 pass_left=1 pass_right=1
    0x00000000,  // [11] leaf / undef
    0x00A45A03,  // [12] feat_id=0 thresh=42074 pass_left=1 pass_right=1
    0x00020000,  // [13] feat_id=0 thresh=512 pass_left=0 pass_right=0
    0x00000000,  // [14] leaf / undef
};
/*
              precision    recall  f1-score   support

      BENIGN       0.97      1.00      0.99      5115
   MALICIOUS       1.00      1.00      1.00     50498

    accuracy                           1.00     55613
   macro avg       0.99      1.00      0.99     55613
weighted avg       1.00      1.00      1.00     55613
*/