#!/usr/bin/env bash
# Auto-generated by main.py.
# Loads decision-tree nodes into a BPF map via bpftool.
#
# Usage: sudo ./update_params.sh <map_id>
#
# Map value layout (8 bytes, little-endian):
#   bytes 0-3 : threshold (__u32 LE)
#   bytes 4-7 : feature   (__u32 LE, MSB flags + feat_idx)

if [ -z "$1" ]; then
    echo "Usage: sudo $0 <map_id>"
    exit 1
fi

MAP_ID="$1"

# node 0: feat_id=3 thresh=210 pass_left=1 pass_right=0
bpftool map update id "$MAP_ID" key hex 00 00 00 00 value hex D2 00 00 00 A3 00 00 00

# node 1: feat_id=0 thresh=49102 pass_left=1 pass_right=1
bpftool map update id "$MAP_ID" key hex 01 00 00 00 value hex CE BF 00 00 E0 00 00 00

# node 2: feat_id=2 thresh=11 pass_left=1 pass_right=0
bpftool map update id "$MAP_ID" key hex 02 00 00 00 value hex 0B 00 00 00 A2 00 00 00

# node 3: feat_id=2 thresh=11 pass_left=1 pass_right=0
bpftool map update id "$MAP_ID" key hex 03 00 00 00 value hex 0B 00 00 00 A2 00 00 00

# node 4: feat_id=1 thresh=37 pass_left=1 pass_right=1
bpftool map update id "$MAP_ID" key hex 04 00 00 00 value hex 25 00 00 00 E1 00 00 00

# node 5: feat_id=1 thresh=261 pass_left=1 pass_right=1
bpftool map update id "$MAP_ID" key hex 05 00 00 00 value hex 05 01 00 00 E1 00 00 00

# node 6: feat_id=4 thresh=69906 pass_left=0 pass_right=1
bpftool map update id "$MAP_ID" key hex 06 00 00 00 value hex 12 11 01 00 64 00 00 00

# node 7: feat_id=0 thresh=528 pass_left=1 pass_right=1
bpftool map update id "$MAP_ID" key hex 07 00 00 00 value hex 10 02 00 00 E0 00 00 00

# node 8: feat_id=1 thresh=1183 pass_left=1 pass_right=0
bpftool map update id "$MAP_ID" key hex 08 00 00 00 value hex 9F 04 00 00 A1 00 00 00

# node 9: leaf / undefined
bpftool map update id "$MAP_ID" key hex 09 00 00 00 value hex 00 00 00 00 00 00 00 00

# node 10: feat_id=3 thresh=0 pass_left=1 pass_right=1
bpftool map update id "$MAP_ID" key hex 0A 00 00 00 value hex 00 00 00 00 E3 00 00 00

# node 11: leaf / undefined
bpftool map update id "$MAP_ID" key hex 0B 00 00 00 value hex 00 00 00 00 00 00 00 00

# node 12: feat_id=0 thresh=38958 pass_left=1 pass_right=1
bpftool map update id "$MAP_ID" key hex 0C 00 00 00 value hex 2E 98 00 00 E0 00 00 00

# node 13: feat_id=0 thresh=512 pass_left=0 pass_right=0
bpftool map update id "$MAP_ID" key hex 0D 00 00 00 value hex 00 02 00 00 20 00 00 00

# node 14: leaf / undefined
bpftool map update id "$MAP_ID" key hex 0E 00 00 00 value hex 00 00 00 00 00 00 00 00

echo "Done loading $MAP_ID nodes."
