// Auto-generated by main.py.
// Include this file in dt_xdp.usr.c to load the decision tree.

#ifndef DT_PARAMS_H
#define DT_PARAMS_H

#define DT_NODE_NB 7

static __u32 trained_dt_nodes[] = {
    0x00001006,  // [0] feat_id=0 thresh=16 pass_left=1 pass_right=0
    0x00000000,  // [1]
    0x00000000,  // [2]
    0x00000000,  // [3] 
    0x00000000,  // [4] 
    0x00000000,  // [5]
    0x00000000,  // [6]
};

#endif /* DT_PARAMS_H */
