#!/usr/bin/env bash
# Auto-generated by main.py.
# Loads decision-tree nodes into a BPF map via bpftool.
#
# Usage: sudo ./update_params.sh <map_id>

if [ -z "$1" ]; then
    echo "Usage: sudo $0 <map_id>"
    exit 1
fi

MAP_ID="$1"
NODE_NB=7

KEYS_MAP0=(
    "01 00 00 00"
    "02 00 00 00"
    "03 00 00 00"
    "04 00 00 00"
    "05 00 00 00"
    "06 00 00 00"
    "07 00 00 00"
)

KEYS_MAP1=(
    "08 00 00 00"
    "09 00 00 00"
    "0A 00 00 00"
    "0B 00 00 00"
    "0C 00 00 00"
    "0D 00 00 00"
    "0E 00 00 00"
    "0F 00 00 00"
)

read_current_map() {
    local out raw
    out=$(bpftool map lookup id "$MAP_ID" key hex 00 00 00 00 2>/dev/null) || return 1

    raw=$(printf "%s" "$out" | grep -oE '"value"[[:space:]]*:[[:space:]]*[0-9]+' | tail -n1 | sed -E 's/.*:[[:space:]]*([0-9]+).*/\1/')
    if [ -z "$raw" ]; then
        raw=$(printf "%s" "$out" | grep -oE "([0-9A-Fa-f]{2} ){3}[0-9A-Fa-f]{2}" | tail -n1)
        if [ -z "$raw" ]; then return 2; fi
        if [ "$raw" = "00 00 00 00" ]; then
            printf "0"
        else
            printf "1"
        fi
        return 0
    fi

    printf "%s" "$raw"
}

VALUES=(
    "06 10 00 00"
    "00 00 00 00"
    "00 00 00 00"
    "00 00 00 00"
    "00 00 00 00"
    "00 00 00 00"
    "00 00 00 00"
)

COMMENTS=(
    "node 0: feat_id=0 thresh=16 pass_left=1 pass_right=0"
    "node 1: leaf / undefined"
    "node 2: leaf / undefined"
    "node 3: leaf / undefined"
    "node 4: leaf / undefined"
    "node 5: leaf / undefined"
    "node 6: leaf / undefined"
    "node 7: leaf / undefined"
)

raw_used=$(read_current_map)
if [ $? -ne 0 ]; then
    echo "Warning: failed to read current map selection from key 0; defaulting to map 0"
    raw_used=0
fi

USED_MAP=$raw_used
echo "current DT map in use : $USED_MAP"

if [ "$USED_MAP" -eq 1 ]; then
    KEYS=("${KEYS_MAP0[@]}")
    TARGET_MAP=0
else
    KEYS=("${KEYS_MAP1[@]}")
    TARGET_MAP=1
fi

echo "filling DT map $TARGET_MAP"

for i in $(seq 0 $((NODE_NB - 1))); do
    IFS=" " read -r k0 k1 k2 k3 <<< "${KEYS[i]}"
    IFS=" " read -r v0 v1 v2 v3 <<< "${VALUES[i]}"
    echo "# ${COMMENTS[i]}"
    bpftool map update id "$MAP_ID" key hex "$k0" "$k1" "$k2" "$k3" value hex "$v0" "$v1" "$v2" "$v3"
    echo
done

if [ "$TARGET_MAP" -eq 0 ]; then
    echo "# switch active DT map selector to map 0"
    bpftool map update id "$MAP_ID" key hex 00 00 00 00 value hex 00 00 00 00
else
    echo "# switch active DT map selector to map 1"
    bpftool map update id "$MAP_ID" key hex 00 00 00 00 value hex 01 00 00 00
fi

echo "Done loading $MAP_ID nodes."
