// eBPF kernel program to trace all network packets (& output them for now)

// Include vmlinux.h for kernel type definitions
// This is generated from kernel BTF and provides ALL kernel types
// It replaces the need for individual kernel headers
#include "vmlinux.h"
#include "../ML/DT/dt_features.h" //needed to have DT_NODE_NB

// libbpf helper macros for CO-RE and BPF operations
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>

// CO-RE helper macros for reading kernel structures safely
// BPF_CORE_READ handles field offset relocations automatically
#include <bpf/bpf_core_read.h>

// Tracing-specific helpers for attaching to tracepoints
#include <bpf/bpf_tracing.h>

// Our shared definitions
#include "ml_dt.h" //contains commons definition (kernel / user) for the decision tree
#include "common.h" //contains commons definitions for all scripts
#include "project_features.h" //contains all features references such as F_D_PORT
#include "../ML/DT/dt_features.h" //contains FEATURES vector and FEATURE_NB int.

//Features and feature_nb will be defined in dt_features.h file generated by Python.

// Declare the license - GPL is required for most BPF helper functions
// This MUST be present or the verifier will reject the program
char LICENSE[] SEC("license") = "GPL";

// Array that contains the DT nodes.
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __type(value, __u32); //3 bytes (24 bits) for threshold (thus features), 6 bits for feature ID and 2 bits for pass left / pass right (in this order)
    __type(key, __u32); //key is always a __u32 (docs.ebpf.io) but we will use a __u8 in our case (casted to a __u32.)
    __uint(max_entries, 2*DT_NODE_NB+1);//hot-update enabled : qstores 2 trees + 1 binary node
} dt_nodes_array SEC(".maps");

//Flow LRU hashmap, to process per-flow features (mean_packet_size & time_since_last_packet). In theory, will only be useful if there is some features that requires flow (FEATURES >> 64 != 0)
struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    // Maximum number of entries in the map (adjust as needed)
    __uint(max_entries, (((FEATURES & F_RANGE_FLOW) != 0) ? 2048 : 1));
    // Key is a __u128 of combined source_ip (32), source_port(16), dest_ip (32), dest_port (16), protocol(8) plus 32 filler bits. (not optimal)
    __type(key, __u128);
    // Value is a struct ip_count containing the count and total bytes
    __type(value, struct flow_info);
} flow_info_map SEC(".maps");

#ifndef SILENT
// Create a ring buffer map that will be used to apss information to the user space. (packets info, timestamps and decision)
struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 1024*16); //16KB
} events_ring SEC(".maps");
#endif

//update feature vector with value if, and only if, feature is needed
//  feature_vector is a vector of __u32 of features values (are actually 24 bits features currently)
static void fvifupdate(__u32 *feature_vector, __u64 feature, __u32 newval) {
    // Only update if the feature is enabled in FEATURES
    if ((FEATURES & feature) == 0)
        return;

    // Compute the index as the number of enabled features below 'feature'.
    // This is equivalent to the previous loop but safer and clearer.
    __u64 lower_mask = FEATURES & (feature - 1);
    int index = __builtin_popcountll(lower_mask);

    // Clamp to 24 bits and store
    feature_vector[index] = newval > 0xFFFFFF ? 0xFFFFFF : newval;
}

// parse the packet located in the context, and fill flow_info_map and the feature vector with the required information.
static inline int parse_update(struct xdp_md *ctx, __u32 fv[], struct netevent *nete) 
{
    // retrieving packet data, size and timestamp
    void *data = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    __u64 time_now = bpf_ktime_get_ns(); //time when the packet was recieved in ns

    //1 parse eth header
    struct ethhdr *eth = data;
    if (eth + 1 > data_end) {
        return -1; // error, packet too short
    }

    //2 check if its IP protocol
    if (eth->h_proto != bpf_htons(ETH_P_IP)) {
        return -2; // not an IP packet
    }

    //3 parse ip header
    struct iphdr *ip = data + sizeof(struct ethhdr);
    if (ip + 1 > data_end) {
        return -3; // error, packet too short for IP header
    }

    #ifndef SILENT
    //4 : fill net_event vector with features if it exists (== if debug)
    if (nete) {
        //copy ip info to ip_debug
        nete->dst_ip = ip->daddr;
        nete->src_ip = ip->saddr;
        nete->protocol = ip->protocol;
        nete->packet_size = (data_end - data); // payload + header 
    }
    #endif


    //5 : fill feature vector (and / or debug info) with packet-based features.
    fvifupdate(fv, F_PROTOCOL, ip->protocol);
    fvifupdate(fv, F_PKT_SIZE, (data_end - data));
    //retrieving ports (TCP or UDP only) only if : ports features needed OR flow features needed (port is in folw ID) OR debug
    __u16 sport = 0;
    __u16 dport = 0;
    if ((FEATURES & (F_S_PORT | F_D_PORT)) || ((FEATURES & F_RANGE_FLOW) != 0) || nete) {
        if (ip->protocol == IPPROTO_TCP) {
            struct tcphdr *tcp = data + sizeof(struct ethhdr) + sizeof(struct iphdr);
            if (tcp + 1 > data_end) {
                return -4; // error, packet too short for TCP header
            }
            sport = bpf_ntohs(tcp->source);
            dport = bpf_ntohs(tcp->dest);
        } else if ((FEATURES & (F_S_PORT | F_D_PORT)) && (ip->protocol == IPPROTO_UDP)) {
            struct udphdr *udp = data + sizeof(struct ethhdr) + sizeof(struct iphdr);
            if (udp + 1 > data_end) {
                return -5; // error, packet too short for UDP header
            }
            sport = bpf_ntohs(udp->source);
            dport = bpf_ntohs(udp->dest);
        }
        if (nete) {
            nete->dst_port = dport;
            nete->src_port = sport;
        }
        fvifupdate(fv, F_D_PORT, dport);
        fvifupdate(fv, F_S_PORT, sport);
    }


    //6 : fill feature vector with flow-based features, if needed.
    if (FEATURES & F_RANGE_FLOW) {
        //retrieve flow key : ips_ports_ipd_portd_protocol
        __u128 flow_key = ((__u128)ip->saddr << 96) | ((__u128)sport << 80) | ((__u128)ip->daddr << 48) | ((__u128)dport << 32);
        struct flow_info *fi = bpf_map_lookup_elem(&flow_info_map, &flow_key);
        if (fi) { //flow exists
            // update flow
            __u64 iat_ms =(__u64)(time_now - fi->last_seen) / 1000000; // ns to ms
            fi->last_seen = time_now; //ns
            __sync_fetch_and_add(&fi->count, 1);
            __sync_fetch_and_add(&fi->tot_bytes, (data_end - data));
            __sync_fetch_and_add(&fi->tot_IAT, iat_ms);
            
            // update feature vector with necessary features:
            fvifupdate(fv, F_SIZE_MEAN, (__u32)(fi->tot_bytes / fi->count));
            fvifupdate(fv, F_SIZE_TOT, fi->tot_bytes);
            fvifupdate(fv, F_PKT_NB, fi->count);
            fvifupdate(fv, F_IAT, iat_ms);
            fvifupdate(fv, F_IAT_TOT, fi->tot_IAT);
            fvifupdate(fv, F_IAT_MEAN, (__u32)(fi->tot_IAT / fi->count));


        } else { //flow does not exists
            //create the new flow entry
            struct flow_info new_fi =   {   time_now, //last_packet
                                            (data_end - data), //tot size
                                            0, //tot IAT
                                            1 //packet nb
                                        }; 
            bpf_map_update_elem(&flow_info_map, &flow_key, &new_fi, BPF_NOEXIST);

            // update feature vector with features that requires flow_info
            fvifupdate(fv, F_SIZE_MEAN, (data_end - data));
            fvifupdate(fv, F_SIZE_TOT, (data_end - data));
            fvifupdate(fv, F_PKT_NB, 1);
            fvifupdate(fv, F_IAT, 0);
            fvifupdate(fv, F_IAT_TOT, 0);
            fvifupdate(fv, F_IAT_MEAN, 0);
        }
    }

    return 0; // success
}

// classify the feature vector, reurns DROP (0) or PASS (1)
static inline int classify_dt(__u32 fv[]) {
    //packet processing (decision tree).
    __u32 i = 0; //index of the current node being processed in the tree (not index in map, index of node)
    __u32 map_idx = 0; //real index of the current node in the dt_nodes map
    bool map_hui = 0; //map hot-update parameter : 0 = first map, 1 = 2nd map
    bool pass = true; //default decision = pass packet
    __u32* node;
    __u32 feature_value;

    //look @ which part of the map to use (maps can store twice the parameters)
    node = bpf_map_lookup_elem(&dt_nodes_array, &map_idx);
    // If the map hasn't been initialized yet, avoid dereferencing a NULL pointer.
    if (!node) {
        return pass ? 1 : 0;
    }
    // 0 -> map is between indexes 1 and DT_NODE_NB (included)
    // 1 -> map is between indexes DT_NODE_NB + 1 and 2*DT_NODES_NB (included)
    map_hui = (*node == 0) ? 0 : 1;



    //have to use a bounded loop in order to allow the ebpf program to understand taht my loop is short
    for (__u8 j = 0; j <= 16; j += 1) { //j = depth
        node = bpf_map_lookup_elem(&dt_nodes_array, &map_idx); //retrieve current node
        //if index too big (arrived @ end of the DT) OR arrived at a leaf / undef : we apply the current decision.
        if ((i >= DT_NODE_NB) || !node || (node == 0)) {
            return pass ? 1 : 0;
        }

        //else, node is defined AND current node is not a leaf, we need to process decision and update the index.
        if (((*node) & 0x000000FC) >> 2 < FEATURE_NB) {
            feature_value = fv[((*node) & 0x000000FC) >> 2];//retrieving feature ID.
        } else {
            //ERROR : feature index out of bounds
            return -1;
        }
        if (feature_value <= ((*node) >> 8)) { //(*node) >> 8 = Threshold
            //go left
            pass = ((*node) & 0x00000002) >> 1;//retrieving pass_left
            i = 2*i + 1;
        } else {
            //go right
            pass = (*node) & 0x00000001;//retrieving pass_right
            i = 2*i + 2;
        }
        // map_hui == 0 -> use indexes 1..DT_NODE_NB
        // map_hui == 1 -> use indexes DT_NODE_NB+1 .. 2*DT_NODE_NB
        map_idx = (map_hui == 0) ? i+1 : i+DT_NODE_NB+1;
    }
}


//XDP network listener main function
SEC("xdp")
int xdp_dt(struct xdp_md *ctx)
{
    //1: parse the packet and update feature vector.
    //struct feature_vector fv = {0}; //initialize feature vector to 0 to avoid issues when encountering errors
    __u32 fv[FEATURE_NB] = {};//create a FEATURE_NB sized array of __u32 for registering the features of our analyzed packet.
    int ret;
    struct netevent *ne;
    #ifndef SILENT
    ne = bpf_ringbuf_reserve(&events_ring, sizeof(struct netevent), 0);
    #endif

    //parse the packet & update the feature vector
    switch (parse_update(ctx, fv, ne)) {
        case -2:
            //Not IP packet (this is not a bad packet, passing it silently (many not-IP packets, we want readability).)
            goto passsilent;
        case 0:
            //success, do nothing (feature vector will be analyzed by the decision tree for drop or pass decision.)
            break;
        case -1:
            //ERROR feature index out of bounds (misconfigured DT nodes)
            goto drop;
        default:
            //any other error (too short for eth header, too short for IP header, too short for TCP/UDP header) = bad packet, drop it.
            goto drop;
    }

    //use the decision tree (stored in dt_nodes_array) to classify the packet as malicious or benign.
    switch (classify_dt(fv)) {
        case 1:
            //pass
            goto pass;
        case 0:
            //drop
            goto drop;
        default:
            //unknown
            goto drop;
    }

drop:
    #ifndef SILENT
    if (ne) {
        ne->decision = 0;
        bpf_ringbuf_submit(ne, 0);
    }
    #endif
    return XDP_DROP; //Not actually dropping packets, might cause issue while testing
dropsilent:
    #ifndef SILENT
    if (ne) {
        bpf_ringbuf_discard(ne, 0);
    }
    #endif
    return XDP_DROP; //Not actually dropping packets, might cause issue while testing
pass:
    #ifndef SILENT
    if (ne) {
        ne->decision = 1;
        bpf_ringbuf_submit(ne, 0);
    }
    #endif
    return XDP_PASS;
passsilent:
    #ifndef SILENT
    if (ne) {
        bpf_ringbuf_discard(ne, 0);
    }
    #endif
    return XDP_PASS;
}