// eBPF kernel program to trace all network packets (& output them for now)

// Include vmlinux.h for kernel type definitions
// This is generated from kernel BTF and provides ALL kernel types
// It replaces the need for individual kernel headers
#include "vmlinux.h"

// libbpf helper macros for CO-RE and BPF operations
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>

// CO-RE helper macros for reading kernel structures safely
// BPF_CORE_READ handles field offset relocations automatically
#include <bpf/bpf_core_read.h>

// Tracing-specific helpers for attaching to tracepoints
#include <bpf/bpf_tracing.h>

// Our shared definitions
#include "ml_dt.h" //contains commons definition (kernel / user) for the decision tree
#include "common.h" //contains commons definitions for all scripts
#include "features.h" //contains all features references such as F_D_PORT
#include "../ML/DT/dt_features.h" //contains FEATURES vector and FEATURE_NB int.

//Features and feature_nb will be defined in dt_features.h file generated by Python.

// Declare the license - GPL is required for most BPF helper functions
// This MUST be present or the verifier will reject the program
char LICENSE[] SEC("license") = "GPL";

// Create a LRU hash maps to count the number of packets and total bytes for each source-destination IP pair
// LRU = Least Recent Used, delete most unused entries once the map is full.
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __type(value, struct dt_node);
    __type(key, __u32); //key is always a __u32 (docs.ebpf.io)
    __uint(max_entries, DT_NODE_NB); //can store 2*DT_NODE_NB+1 to enable hot_updates (first node will have an unreferenced feature index and be "the boolean")
} dt_nodes_array SEC(".maps");

//Flow LRU hashmap, to process per-flow features (mean_packet_size & time_since_last_packet). In theory, will only be useful if there is some features that requires flow (FEATURES >> 64 != 0)
struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    // Maximum number of entries in the map (adjust as needed)
    __uint(max_entries, (((FEATURES & F_RANGE_FLOW) != 0) ? 2048 : 0));
    // Key is a __u128 of combined source_ip (32), source_port(16), dest_ip (32), dest_port (16), plus 32 filler bits. (not optimal)
    __type(key, __u128);
    // Value is a struct ip_count containing the count and total bytes
    __type(value, struct flow_info);
} flow_info_map SEC(".maps");

// Create a ring buffer map that will be used only if DEBUG == true.
struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, DEBUG ? 1024*16 : 0); //16KB
} events_ring SEC(".maps");


// parse the packet located in the context, and fill flow_info_map and the feature vector with the required information.
static inline int parse_update(struct xdp_md *ctx, __u32 fv[], struct netevent *nete) //TODO: update with netevent use and remove the debug_info structure
{
    // retrieving packet data, size and timestamp
    void *data = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    __u64 time_now = bpf_ktime_get_ns();

    //1 parse eth header
    struct ethhdr *eth = data;
    if (eth + 1 > data_end) {
        return -1; // error, packet too short
    }

    //2 check if its IP protocol
    if (eth->h_proto != bpf_htons(ETH_P_IP)) {
        return -2; // not an IP packet
    }

    //3 parse ip header
    struct iphdr *ip = data + sizeof(struct ethhdr);
    if (ip + 1 > data_end) {
        return -3; // error, packet too short for IP header
    }

    //4 : fill net_event vector with features if it exists (if debug)
    if (nete) {
        //copy ip info to ip_debug
        nete->dst_ip = ip->daddr;
        nete->src_ip = ip->saddr;
        nete->protocol = ip->protocol;
        nete->packet_size = (__u16)(data_end - data);
    }


    //5 : fill feature vector (and / or debug info) with packet-based features.
    if ((FEATURES & F_PROTOCOL) != 0) {
        //if protocol is part of the features:
        fv[get_feature_vector_index(FEATURES, FEATURE_NB, F_PROTOCOL)] = ip->protocol;
    }
    if ((FEATURES & F_PKT_SIZE) != 0) {
        //if packet size is part of the features:
        fv[get_feature_vector_index(FEATURES, FEATURE_NB, F_PKT_SIZE)] = (__u16)(data_end - data);
    }
    //retrieving ports (TCP or UDP only) only if : ports features needed OR flow features needed (port is in folw ID) OR debug
    __u16 sport;
    __u16 dport;
    if ((FEATURES & (F_S_PORT | F_D_PORT)) || ((FEATURES & F_RANGE_FLOW) != 0) || nete) {
        if (ip->protocol == IPPROTO_TCP) {
            struct tcphdr *tcp = data + sizeof(struct ethhdr) + sizeof(struct iphdr);
            if (tcp + 1 > data_end) {
                return -4; // error, packet too short for TCP header
            }
            sport = bpf_ntohs(tcp->source);
            dport = bpf_ntohs(tcp->dest);
        } else if ((FEATURES & (F_S_PORT | F_D_PORT)) && (ip->protocol == IPPROTO_UDP)) {
            struct udphdr *udp = data + sizeof(struct ethhdr) + sizeof(struct iphdr);
            if (udp + 1 > data_end) {
                return -5; // error, packet too short for UDP header
            }
            sport = bpf_ntohs(udp->source);
            dport = bpf_ntohs(udp->dest);
        } else {
            sport = 0;
            dport = 0;
        }
        if (nete) {
            nete->dst_port = dport;
            nete->src_port = sport;
        }

        if ((FEATURES & F_D_PORT) != 0) {
            //if protocol is part of the features:
            fv[get_feature_vector_index(FEATURES, FEATURE_NB, F_D_PORT)] = dport;
        }
        if ((FEATURES & F_S_PORT) != 0) {
            //if packet size is part of the features:
            fv[get_feature_vector_index(FEATURES, FEATURE_NB, F_S_PORT)] = sport;
        }
    }


    //6 : fill feature vector with flow-based features.
    if ((FEATURES & F_RANGE_FLOW) != 0) {
        __u128 flow_key = ((__u128)ip->saddr << 96) | ((__u128)sport << 80) | ((__u128)ip->daddr << 48) | ((__u128)dport << 32);
    }




    //5 retrieve & update flow information, then fill the rest of feature vector.
    
    struct flow_info *fi = bpf_map_lookup_elem(&flow_info_map, &flow_key);
    if (fi) {
        // flow already created (one packet already seen for this flow)
        //process time since last packet. !! convert to ms and __u32
        __u64 tsl = (time_now - fi->last_seen) / 1000000;
        //process (new) mean packet size
        __sync_fetch_and_add(&fi->count, 1);
        __sync_fetch_and_add(&fi->tot_bytes, fv->packet_size);

        // update feature vector with features that requires flow_info
        fv->mean_packet_size = (__u16)(fi->tot_bytes / fi->count);
        //handle time longer than max value of __u32 (49.7 days ...), by capping it to the max value.
        if (tsl > 0xFFFFFFFF) {
            fv->time_since_last_packet = 0xFFFFFFFF;
        } else {
            fv->time_since_last_packet = (__u32)tsl;
        }
        fi->last_seen = time_now;
    } else {
        //create the new flow entry
        struct flow_info new_fi = { time_now, fv->packet_size, 1 };
        bpf_map_update_elem(&flow_info_map, &flow_key, &new_fi, BPF_NOEXIST);
        // update feature vector with features that requires flow_info
        fv->time_since_last_packet = 0;
        fv->mean_packet_size = fv->packet_size; //only one packet seen
    }
    return 0; // success
}

// classify the feature vector, reurns DROP (0) or PASS (1)
static inline int classify_dt(__u32 fv[]) {
    //packet processing (decision tree).
    __u8 i = 0; //index of the root node of the tree. u8 since it prevents the verifier to think it can be enormous while testing.
    int pass = true; //default decision = pass;
    struct dt_node *node;
    __u32 feature_value;

    //have to use a bpf loop helper function in order to allow the ebpf program to understand taht my loop is short
    for (__u8 j = 0; j <= DT_NODE_NB; j *= 2) {
        node = bpf_map_lookup_elem(&dt_nodes_array, &i);
        //if node undefined (tree not initialized), index too big (arrived @ end of the DT),or arrived at a leaf (3rd MSB = 0): we apply the current decision.
        if (!node || ((node->feature & 0b00100000) == 0) || (i > DT_NODE_NB)) {
            if (pass) {
                return 1; //pass
            } else {
                return 0; //drop
            }
        }

        //else, node is defined AND current node is not a leaf, we need to process decision and update the index.
        feature_value = fv[node->feature & 0x1F]; //index in the vector is directly equal to the index stored in the DT nodes
        if (feature_value <= node->threshold) {
            //go left
            pass = node->feature & 0b10000000;
            i = 2*i + 1;
        } else {
            //go right
            pass = node->feature & 0b01000000;
            i = 2*i + 2;
        }
    }
}

//return feature index in the feature vector, given the feature descriptor (128-bit vector), the features total number, and the wanted feature index unique's ID (ex: F_S_PORT)
static inline int get_feature_vector_index(int features, int feature_nb, int feature) {
    int index = 0;
    for (int curr_f = 1; curr_f <= feature; curr_f = curr_f << 1)
    {
        //loop for each feature, starting from the LSB features.
        if ((curr_f & features) != 0) {
            // if this feature is present in the chosen features :
            index++;
        }
    }
    return index;
}

//XDP network listener main function
SEC("xdp")
int xdp_trace_net_event(struct xdp_md *ctx)
{
    //1: parse the packet and update feature vector.
    //struct feature_vector fv = {0}; //initialize feature vector to 0 to avoid issues when encountering errors
    __u32 fv[FEATURE_NB];//create a FEATURE_NB sized array of __u32 for registering the features of our analyzed packet.
    int ret;
    struct netevent ne = (struct netevent){0}; //initialize ipd to 0 to avoid issues when encountering errors

    //parse the packet & update the feature vector
    switch (DEBUG ? parse_update(ctx, fv, &ne) : parse_update(ctx, fv, NULL)) {
        case -2:
            //Not IP packet (this is not a bad packet, passing it silently (many not-IP packets, we want readability).)
            goto passsilent;
        case 0:
            //success, do nothing (feature vector will be analyzed by the decision tree for drop or pass decision.)
            break;
        default:
            //any other error (too short for eth header, too short for IP header, too short for TCP/UDP header) = bad packet, drop it.
            goto drop;
    }

    //use the decision tree (stored in dt_nodes_array) to classify the packet as malicious or benign.
    switch (classify_dt(fv)) {
        case 1:
            //pass
            goto pass;
        case 0:
            //drop
            goto drop;
        default:
            //unknown
            goto drop;
    }

drop:
    if (DEBUG) {
        //create debug info and send it to the user space via ring buffer
        struct debug_info *d = bpf_ringbuf_reserve(&events_ring, sizeof(struct debug_info), 0);
        //TODO fill with netevent instead of this new redondant debug_info struct
        if (d) {
            d->src_ip = ipd.saddr;
            d->dst_ip = ipd.daddr;
            d->src_port = fv.source_port;
            d->dst_port = fv.dest_port;
            d->packet_size = fv.packet_size;
            d->protocol = fv.protocol;
            d->decision = false; //drop
            bpf_ringbuf_submit(d, 0);
        }
    }
dropsilent:
    return XDP_PASS; //Not actually dropping packets, might cause issue while testing
pass:
    if (DEBUG) {
        //TODO fill with netevent instead of this new redondant debug_info struct
        //create debug info and send it to the user space via ring buffer.
        struct debug_info *d = bpf_ringbuf_reserve(&events_ring, sizeof(struct debug_info), 0);
        if (d) {
            d->src_ip = ipd.saddr;
            d->dst_ip = ipd.daddr;
            d->src_port = fv.source_port;
            d->dst_port = fv.dest_port;
            d->packet_size = fv.packet_size;
            d->protocol = fv.protocol;
            d->decision = true; //pass
            bpf_ringbuf_submit(d, 0);
        }
    }
passsilent:
    return XDP_PASS;
}