// src/main.c
// User-space program to load and interact with the eBPF program
// Uses the auto-generated skeleton for type-safe program management

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <sys/resource.h>

// libbpf library header for core BPF functionality
#include <bpf/libbpf.h>

// Include our generated skeleton header
// The skeleton provides type-safe access to maps, programs, and links
#include "first.skel.h"

// Our shared definitions (same file used by eBPF program)
#include "common.h"

// Global flag for graceful shutdown
// Marked volatile because it's modified by signal handler
static volatile sig_atomic_t exiting = 0;

// Signal handler for graceful shutdown (Ctrl+C)
// Sets the exiting flag to stop the main event loop
static void sig_handler(int sig)
{
    // Signal number is unused but required by handler signature
    (void)sig;
    exiting = 1;
}

// Callback function invoked for each event from the ring buffer
// This is called by libbpf's ring buffer polling mechanism
static int print_netevent(void *ctx, void *data, size_t data_sz)
{
    // Suppress unused parameter warning
    // ctx could be used to pass user-defined context
    (void)ctx;

    // Cast the raw data to our event structure
    // The data comes directly from bpf_ringbuf_submit in kernel
    const struct event *e = data;

    // Validate the data size matches our expected structure
    // This is a safety check - sizes should always match
    if (data_sz < sizeof(*e)) {
        fprintf(stderr, "Error: event size mismatch\n");
        return 0;
    }

    // Print the event information
    // Format: PID, UID, command name, and executed filename
    printf("%-8d %-8d %-16s %s\n",
           e->pid,      // Process ID
           e->uid,      // User ID
           e->comm,     // Command name (parent process)
           e->filename  // Executed filename/path
    );

    // Return 0 to continue processing events
    // Non-zero would stop the ring buffer consumer
    return 0;
}

// Custom libbpf print callback for logging
// Filters out debug messages to reduce noise
static int libbpf_print_fn(enum libbpf_print_level level,const char *format,va_list args)
{
    // Only print warnings and errors, skip debug messages
    if (level == LIBBPF_DEBUG)
        return 0;

    // Print to stderr with the format string and arguments
    return vfprintf(stderr, format, args);
}

int main(int argc, char **argv)
{
    // Suppress unused parameter warnings
    (void)argc;
    (void)argv;

    // Pointer to our BPF skeleton structure
    // This is generated by bpftool and contains all program/map references
    struct first_bpf *skel = NULL;

    // Ring buffer pointer for receiving events
    struct ring_buffer *rb = NULL;

    // Return code for error handling
    int err;

    // Set up custom libbpf logging
    // This filters debug messages for cleaner output
    libbpf_set_print(libbpf_print_fn);

    // STEP 1: Open the BPF skeleton
    // This parses the embedded ELF data but doesn't load into kernel yet
    // Returns NULL on failure
    skel = first_bpf__open();
    if (!skel) {
        fprintf(stderr, "Failed to open BPF skeleton\n");
        return 1;
    }

    // STEP 2: Load and verify the BPF programs
    // This loads bytecode into kernel and runs the verifier
    // The verifier ensures the program is safe to run
    err = first_bpf__load(skel);
    if (err) {
        fprintf(stderr, "Failed to load & verify BPF skeleton: %d\n", err);
        goto cleanup;
    }

    // STEP 3: Attach the BPF programs to their hooks
    // For our tracepoint program, this attaches to sys_enter_execve
    // The skeleton knows where to attach based on SEC() annotations
    err = first_bpf__attach(skel);
    if (err) {
        fprintf(stderr, "Failed to attach BPF skeleton: %d\n", err);
        goto cleanup;
    }

    // STEP 4: Set up signal handlers for graceful shutdown
    // SIGINT = Ctrl+C, SIGTERM = kill command
    signal(SIGINT, sig_handler);
    signal(SIGTERM, sig_handler);

    // STEP 5: Create ring buffer consumer
    // Arguments: file descriptor of ring buffer map, callback function, context
    // bpf_map__fd() returns the file descriptor for the 'events' map
    rb = ring_buffer__new(bpf_map__fd(skel->maps.events),
                          print_netevent,  // Callback for each event
                          NULL,          // Context (unused)
                          NULL);         // Options (use defaults)
    if (!rb) {
        err = -1;
        fprintf(stderr, "Failed to create ring buffer\n");
        goto cleanup;
    }

    // Print header for the output table
    printf("%-8s %-8s %-16s %s\n", "PID", "UID", "COMM", "FILENAME");

    // STEP 6: Main event loop
    // Poll the ring buffer for events until exit signal received
    while (!exiting) {
        // Poll with 20ms timeout
        // Returns number of events consumed, or negative on error
        err = ring_buffer__poll(rb, 20 /* timeout in ms */);

        // Handle interruption by signal
        if (err == -EINTR) {
            err = 0;
            break;
        }

        // Handle actual errors
        if (err < 0) {
            fprintf(stderr, "Error polling ring buffer: %d\n", err);
            break;
        }
        // err > 0 means we processed that many events (handled by callback)
    }

cleanup:
    // Clean up resources in reverse order of creation

    // Free the ring buffer
    ring_buffer__free(rb);

    // Destroy the skeleton (detaches programs, closes maps)
    first_bpf__destroy(skel);

    return err < 0 ? 1 : 0;
}